site_name: Incident Response
site_url: https://cmdcndexternal.github.io/IncidentResponse/
repo_url: https://github.com/cmdcndexternal/IncidentResponse
edit_uri: edit/main/docs
theme:
  name: material

# Configuration
theme:
  name: material
  custom_dir: src/.overrides
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[/s/-,:!=/[/]()"`/]+|/.(?!/d)|&[lg]t;|(?!/b)(?=[A-Z][a-z])'
#  - minify:
#      minify_html: true

# Hooks
hooks:
  - src/.overrides/hooks/translations.py

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/squidfunk
#    - icon: fontawesome/brands/gitter
#      link: https://gitter.im/squidfunk/mkdocs-material
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/mkdocs-material/
#    - icon: fontawesome/brands/mastodon
#      link: https://fosstodon.org/@squidfunk
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 1.Preparation: 1.Preparation\README.md
    - 1.01-Troop Leading Procedures: 1.Preparation/1.01-Troop_Leading_Procedures/README.md
    - 1.02-Receive Mission: 1.Preparation/1.02-Receive_Mission/README.md
    - 1.03-Personnel Status: 1.Preparation/1.03-Personnel_Status/README.md
    - 1.04-Legal Support: 1.Preparation/1.04-Legal_Support/README.md
    - 1.05-Partner Engagements: 1.Preparation/1.05-Partner_Engagements/README.md
    - 1.06-Create and Execute IR Orders: 1.Preparation/1.06-Create_and_Execute_IR_Orders/README.md
    - 1.07-Integrate Additional Support: 1.Preparation/1.07-Integrate_Additional_Support/README.md
    - 1.08-Mission Intent: 1.Preparation/1.08-Mission_Intent/README.md
    - 1.09-Continuous AAR: 1.Preparation/1.09-Continuous_AARs/README.md
    - 1.10-Incident Tracking and Reporting: 1.Preparation/1.10-Incident_Tracking_and_Reporting/README.md
    - 1.13-Review Information Security Policies Constraint: 1.Preparation/1.13-Review_Information_Security_Policies_Constraint/README.md
    - 1.14-Request Logs: 1.Preparation/1.14-Request_Logs/README.md
    - 1.15-Interview Network Owner: 1.Preparation/1.15-Interview_Network_Owner/README.md
    - 1.16-Establish Network Owner Priorities Objectives: 1.Preparation/1.16-Establish_Network_Owner_Priorities_Objectives/README.md
    - 1.17-Establish Mission Log: 1.Preparation/1.17-Establish_Mission_Log/README.md
    - 1.17.1-Establish Mission Log Files: https://github.com/cmdcndexternal/IncidentResponse/tree/main/docs/1.Preparation/1.17-Establish_Mission_Log
    - 1.18-Request Network Accounts: 1.Preparation/1.18-Request_Network_Accounts/README.md
    - 1.19-Legal Authorities Regulatory Constraints: 1.Preparation/1.19-Legal_Authorities_Regulatory_Constraints/README.md
    - Preparation References: https://github.com/cmdcndexternal/IncidentResponse/tree/main/docs/1.Preparation/Preparation_References

